jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"

    - name: Run R script
      run: Rscript your_script.R

    - name: Check file existence
      run: |
        if [ -f "event_reg.rds" ]; then
          git add event_reg.rds
          git commit -m 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        else
          echo "event_reg.rds file not found"
        fi
